# Generated by Django 2.2 on 2019-05-03 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NasaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAMERA_ID', models.IntegerField()),
                ('CAMERA_NAME', models.CharField(max_length=100)),
                ('EARTH_DATE', models.CharField(max_length=20)),
                ('IMG_SRC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NasaWallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITLE', models.CharField(max_length=50)),
                ('HDURL', models.CharField(max_length=100)),
                ('IMG_SRC', models.CharField(max_length=100)),
            ],
        ),
    ]
